ESourcing.UI/Models/ErrorViewModel.cs
using System;

namespace ESourcing.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ESourcing.UI/Controllers/AuctionController.cs
using ESourcing.Core.Repositories;
using ESourcing.Core.ResultModels;
using ESourcing.Infrastructure.Repository;
using ESourcing.UI.Clients;
using ESourcing.UI.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ESourcing.UI.Controllers
{
    
    public class AuctionController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly ProductClient _productClient;
        private readonly AuctionClient _auctionClient;
        private readonly BidClient _bidClient;
        public AuctionController(IUserRepository userRepository,ProductClient productClient, AuctionClient auctionClient,BidClient bidClient)
        {
            _userRepository = userRepository;
            _productClient = productClient;
            _auctionClient = auctionClient;
            _bidClient = bidClient;
        }

        public async Task<IActionResult> Index()
        {
            var auctionList = await _auctionClient.GetAuctions();
            if (auctionList.IsSuccess)
            {
                return View(auctionList.Data);
            }
            var emptyList = new List<AuctionViewModel>();
            return View(emptyList);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            //Product GetAll
            var productList = await _productClient.GetProducts();
            if (productList.IsSuccess)
            {
                ViewBag.ProductList = productList.Data;
            }
            var userList = await _userRepository.GetAllAsync();
            ViewBag.UserList = userList;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AuctionViewModel model)
        {
            model.Status = default(int);  
            model.CreatedAt = DateTime.Now;
            model.IncludedSellers.Add(model.SellerId);
            model.FinishedAt = model.FinishedAt;
            model.StartedAt = model.StartedAt;
            var createAuction = await _auctionClient.CreateAuction(model);
            if (createAuction.IsSuccess)
                return RedirectToAction("Index");
            return View(model);
        }
        public async Task<IActionResult> Detail(string id)
        {
            AuctionBidsViewModel model = new AuctionBidsViewModel();
            var auctionResponse = await _auctionClient.GetAuctionById(id);
            var bidsResponse = await _bidClient.GetAllBidsByAuctionId(id);
            model.SellerUserName = HttpContext.User?.Identity.Name;
            model.AuctionId = auctionResponse.Data.Id;
            model.ProductId = auctionResponse.Data.ProductId;
            model.Bids = bidsResponse.Data;
            var isAdmin = HttpContext.Session.GetString("IsAdmin");
            model.IsAdmin = Convert.ToBoolean(isAdmin);

            return View(model);
        }
        [HttpPost]
        public async Task<Result<string>> SendBid(BidViewModel model)
        {
            model.CreateAt = DateTime.Now;
            var sendBidResponse = await _bidClient.SendBid(model);
            return sendBidResponse;
        }
        public async Task<Result<string>> CompleteBid(string id)
        {
            var completeBidResponse = await _auctionClient.CompleteBid(id);
            return completeBidResponse;
        }
    }
}

ESourcing.UI/Controllers/HomeController.cs
using ESourcing.Core.Entities;
using ESourcing.UI.Models;
using ESourcing.UI.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ESourcing.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppUser _user;
        public UserManager<AppUser> _userManager { get; }
        public SignInManager<AppUser> _signInManager { get; }

        public HomeController(AppUser user, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _user = user;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model,string returnUrl)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                if (user != null)
                {
                    //Cookie temizleme
                    await _signInManager.SignOutAsync();
                    //lockoutOnFailure hatalı girişlerde bekletme
                    var result = await _signInManager.PasswordSignInAsync(user, model.Password, false, false);
                    if (result.Succeeded)
                    {
                        HttpContext.Session.SetString("IsAdmin", user.IsAdmin.ToString());
                        //return RedirectToAction("Index", "Home");
                        return LocalRedirect(returnUrl);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Email or password address is not valid.");
                        return View(model);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Email or password address is not valid.");
                    return View(model);
                }
            }
            return View();
        }
        public IActionResult Logout()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Login", "Home");
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(AppUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                _user.FirstName = model.FirstName;
                _user.Email = model.Email;
                _user.LastName = model.LastName;
                _user.PhoneNumber = model.PhoneNumber;
                _user.UserName = model.UserName;
                if (model.UserSelectTypeId=="1")
                {
                    _user.IsBuyer = true;
                    _user.IsSeller = false;
                }
                else
                {
                    _user.IsSeller = true;
                    _user.IsBuyer = false;
                }

                var result = await _userManager.CreateAsync(_user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Login", "Home");
                }
                else
                {
                    foreach (IdentityError item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View(model);
        }
    }
}

ESourcing.UI/Views/Auction/Create.cshtml
@model AuctionViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="card card-primary card-outline">
        <div class="card-body">
            <h4>Auction Create Page Step</h4>
            <div class="row">
                <div class="col-5 col-sm-3">
                    <div class="nav flex-column nav-tabs h-100" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" id="vert-tabs-home-tab" data-toggle="pill" href="#vert-tabs-home" role="tab" aria-controls="vert-tabs-home" aria-selected="true">General Info</a>
                        <a class="nav-link" id="vert-tabs-profile-tab" data-toggle="pill" href="#vert-tabs-profile" role="tab" aria-controls="vert-tabs-profile" aria-selected="false">Product Select</a>
                        <a class="nav-link" id="vert-tabs-messages-tab" data-toggle="pill" href="#vert-tabs-messages" role="tab" aria-controls="vert-tabs-messages" aria-selected="false">Seller Select</a>

                    </div>
                </div>
                <div class="col-7 col-sm-9">
                    <div class="tab-content" id="vert-tabs-tabContent">

                        <div id="vert-tabs-home" class="text-left show active tab-pane fade card card-primary" role="tabpanel" aria-labelledby="vert-tabs-home-tab">
                            <div class="card-header">
                                <h3 class="card-title">General Info Inputs</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="Name">Auction Name</label>
                                    @Html.TextBoxFor(x => x.Name, new { placeholder = "Enter Auction Name", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="Description">Auction Description</label>
                                    @Html.TextBoxFor(x => x.Description, new { placeholder = "Enter Auction Description", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="Description">Auction Quantity</label>
                                    @Html.TextBoxFor(x => x.Quantity, new { placeholder = "Enter Quantity", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Start Date:</label>
                                    <input type="datetime-local" asp-for="StartedAt" value="2021-01-01T03:35">
                                </div>
                                <div class="form-group">
                                    <label>Finish Date:</label>
                                    <input type="datetime-local" asp-for="FinishedAt" value="2021-01-01T03:35">
                                </div>
                            </div>
                        </div>
                        <div class="text-left tab-pane fade card card-warning" id="vert-tabs-profile" role="tabpanel" aria-labelledby="vert-tabs-profile-tab">
                            <div class="card-header">
                                <h3 class="card-title">Product Info Input</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.DropDownListFor(l => l.ProductId, new SelectList(ViewBag.ProductList, "Id", "Name"), "Please Select Product", new { @class = "custom-select form-control col-sm-6" })
                                </div>
                            </div>
                        </div>
                        <div class="text-left tab-pane fade card card-danger" id="vert-tabs-messages" role="tabpanel" aria-labelledby="vert-tabs-messages-tab">
                            <div class="card-header">
                                <h3 class="card-title">Seller Info Input</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.DropDownListFor(l => l.SellerId, new SelectList(ViewBag.UserList, "Id", "FirstName"), "Please Select Seller", new { @class = "custom-select form-control col-sm-6" })
                                </div>
                                <div class="clearfix form-actions">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Create Auction" class="btn btn-info col-xs-3" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>

ESourcing.UI/Views/Auction/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
}
<br />
@model AuctionBidsViewModel

<div class="row">
    <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Quick Auction</h3>
            </div>
            <form method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPrice">Price</label>
                        <input type="number" min="0" class="form-control" id="exampleInputPrice" placeholder="Enter Price" />
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" id="sendButton" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card-header" style="background-color:darkgrey">
            <h3 class="card-title">Active Auction Detail</h3>
        </div>
        @Html.HiddenFor(x => x.AuctionId)
        @Html.HiddenFor(x => x.ProductId)
        @Html.HiddenFor(x => x.SellerUserName)
        <div class="card-body">
            <table id="exampleAuction" class="table table-bordered table-hover">
                <thead>
                    <tr style="background-color:darkgrey">
                        <th>Auction User Name</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody class="bidLine">
                    @if (Model.Bids != null)
                    {
                        @foreach (var item in Model.Bids)
                        {
                            <tr>
                                <td>@item.SellerUserName</td>
                                <td>@item.Price</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<button type="submit" id="finishButton" class="btn btn-primary">
    Finish RFQ
</button>



<script src="~/lib/microsoft-signalr/signalr.js"></script>
<script src="~/js/Views/RFQ/detail.js"></script>

ESourcing.UI/Views/Auction/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<AuctionViewModel>

<br />
<h1>Auction Index</h1>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Active Auction List</h3>
            </div>
            <div class="card-body">
                <table id="example1" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Quantity</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                            <td>@item.Quantity</td>
                            <td>@item.StartedAt.ToShortDateString()</td>
                            <td>@item.FinishedAt.ToShortDateString()</td>
                            <td>
                                @if (item.Status == 1)
                                {
                                    <a asp-route-id="@item.Id" class="btn btn-danger">Closed</a>
                                }
                                else
                                {
                                    <a asp-controller="Auction" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-warning">Details</a>
                                }
                            </td>

                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

ESourcing.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="d-flex justify-content-center align-items-center pt-5 mt-5">
    <div>
        <h1 class="text-danger">E - AUCTION <span class="text-purple">PORTAL</span></h1>
    </div>
</div>

ESourcing.UI/Views/Home/Login.cshtml
@model ESourcing.UI.ViewModel.LoginViewModel

@{
    ViewData["Title"] = "Login";
}
<br />
<h1>Login</h1>

<hr />
<div class="row">
    <div class="col-md-4 offset-md-4">
        <form asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ESourcing.UI/Views/Home/SignUp.cshtml
@model ESourcing.UI.ViewModel.AppUserViewModel

@{
    ViewData["Title"] = "SignUp";
}
<br />
<h1>User Register Form</h1>

<hr />
<div class="row">
    <div class="col-md-4 offset-md-4">
        <form asp-action="SignUp" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>User Type Select</label>
                <select class="custom-select" asp-for="UserSelectTypeId">
                    <option selected="selected" value="1">IsBuyer</option>
                    <option value="2">IsSeller</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ESourcing.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>E-Auction</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">


        <!-- Preloader -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item p-3">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a href="/" class="d-block">Welcome, @UserManager.GetUserName(User)</a>

                            <li class="nav-item has-treeview">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-copy"></i>
                                    <p>Auction Operations</p>
                                    <i class="fas fa-angel-left right"></i>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a asp-controller="Auction" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Auction List</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Auction" asp-action="Create" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Auction Create</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a asp-controller="Auction" asp-action="Index" class="nav-item nav-link">
                                    <i class="nav-icon far fa-calendar-check"></i>
                                    <p>Auction List</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Home" asp-action="Logout" class="nav-item nav-link">
                                    <i class="nav-icon far fa-user"></i>
                                    <p>Logout</p>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-item nav-link" asp-controller="Home" asp-action="SignUp">
                                    <i class="nav-icon far fa-user"></i>
                                    <p>Sing Up</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-item nav-link" asp-controller="Home" asp-action="Login">
                                    <i class="nav-icon far fa-user"></i>
                                    <p>Login</p>
                                </a>
                            </li>
                        }

                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">

                <!-- Main content -->
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
        </div>
        <!-- ./wrapper -->
        <!-- jQuery -->
        <script src="~/plugins/jquery/jquery.min.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
        <script>
            $.widget.bridge('uibutton', $.ui.button)
        </script>
        <!-- Bootstrap 4 -->
        <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- ChartJS -->
        <script src="~/plugins/chart.js/Chart.min.js"></script>
        <!-- Sparkline -->
        <script src="~/plugins/sparklines/sparkline.js"></script>
        <!-- JQVMap -->
        <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
        <!-- jQuery Knob Chart -->
        <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
        <!-- daterangepicker -->
        <script src="~/plugins/moment/moment.min.js"></script>
        <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
        <!-- Tempusdominus Bootstrap 4 -->
        <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
        <!-- Summernote -->
        <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
        <!-- overlayScrollbars -->
        <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
        <!-- AdminLTE App -->
        <script src="~/dist/js/adminlte.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="~/dist/js/demo.js"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src="~/dist/js/pages/dashboard.js"></script>
    </body>
</html>